name: test and publish

on:
    # # TODO re-enable these when ready:
    # push:
    #     branches: [master]
    #     tags: ["v*"]
    #
    # pull_request:
    #   branches: [ master ] # careful what access these builds get, i.e. to secrets (put sensitive stuff into environments for restricted access?)
    workflow_dispatch: # Add manual trigger

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22 
                  cache: "npm"

            - name: install shells
              run: |
                  sudo apt-get update
                  sudo apt-get install -y zsh fish

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    publish:
        needs: test
        runs-on: ubuntu-latest

        if: startsWith(github.ref, 'refs/tags/') # only if it's a tag

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            # yes I could consolidate into one job but releases are rare so keep separate so I can easily add more steps (i.e. probably set release notes in GH release too, not just tag as is now)
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
